<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.Prometheus.Metrics" />
        <PackageReference Include="AspNetCore.HealthChecks.Redis" />
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
        <PackageReference Include="Quartz" />
        <PackageReference Include="Quartz.Extensions.Hosting" />
        <PackageReference Include="Quartz.Serialization.SystemTextJson" />
        <PackageReference Include="RabbitMQ.Client" />
        <PackageReference Include="ZLogger" />
        <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FinanceTracker.Contracts\FinanceTracker.Contracts.csproj" />
        <ProjectReference Include="..\FinanceTracker.Core\FinanceTracker.Core.csproj" />
    </ItemGroup>

</Project>