<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-FinanceTracker.Worker.DomainEventOutbox-6f3d8d74-d18c-4b0c-8158-841906fedbd8</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
        <PackageReference Include="Quartz" Version="3.18.1" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
        <PackageReference Include="Quartz.AspNetCore" Version="3.18.1" />
        <PackageReference Include="ZLogger" Version="2.5.10" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\FinanceTracker.Contracts\FinanceTracker.Contracts.csproj" />
        <ProjectReference Include="..\FinanceTracker.Infrastructure\FinanceTracker.Infrastructure.csproj" />
        <ProjectReference Include="..\FinanceTracker.Worker.Shared\FinanceTracker.Worker.Shared.csproj" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
</Project>