services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nullReference@@1743
      POSTGRES_DB: FinanceTracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4.3.0-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ENABLED_PLUGINS_FILE: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: >
      sh -c "echo '[rabbitmq_management].' > /etc/rabbitmq/enabled_plugins && rabbitmq-server"

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: