<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-FinanceTracker.Worker.BaseCurrencyRecalculation-9f4c1e2a-7d63-4a58-bb90-1c5e83f4d217</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Quartz" />
        <PackageReference Include="Quartz.Extensions.Hosting" />
        <PackageReference Include="ZLogger" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FinanceTracker.Core\FinanceTracker.Core.csproj" />
        <ProjectReference Include="..\FinanceTracker.Infrastructure\FinanceTracker.Infrastructure.csproj" />
        <ProjectReference Include="..\FinanceTracker.Worker.Shared\FinanceTracker.Worker.Shared.csproj" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>
</Project>