<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>03132ba2-1a8b-4141-9a35-1c4b260023b2</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FinanceTracker.Application\FinanceTracker.Application.csproj" />
        <ProjectReference Include="..\FinanceTracker.Infrastructure\FinanceTracker.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
      <PackageReference Include="Microsoft.OpenApi" />
      <PackageReference Include="Scalar.AspNetCore" />
    </ItemGroup>

</Project>
