<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="dbup-postgresql" Version="7.0.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    </ItemGroup>
    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
      <None Remove="Migrations\V001__init.sql" />
      <EmbeddedResource Include="Migrations\V001__init.sql" />
      <None Remove="Migrations\V002__add_outbox_indexes.sql" />
      <EmbeddedResource Include="Migrations\V002__add_outbox_indexes.sql" />
      <None Remove="Migrations\V003__add_unresolvable_events.sql" />
      <EmbeddedResource Include="Migrations\V003__add_unresolvable_events.sql" />
      <None Remove="Migrations\V004__fix_indexes.sql" />
      <EmbeddedResource Include="Migrations\V004__fix_indexes.sql" />
      <None Remove="Migrations\V005__add_user_sessions.sql" />
      <EmbeddedResource Include="Migrations\V005__add_user_sessions.sql" />
      <None Remove="Migrations\V006__add_domain_event_outbox.sql" />
      <EmbeddedResource Include="Migrations\V006__add_domain_event_outbox.sql" />
      <None Remove="Migrations\V007__add_read-model_Indexes.sql" />
      <EmbeddedResource Include="Migrations\V007__add_read-model_Indexes.sql" />
    </ItemGroup>

</Project>
