TRUNCATE qrtz_fired_triggers,
	qrtz_simple_triggers,
	qrtz_simprop_triggers,
	qrtz_cron_triggers,
	qrtz_blob_triggers,
	qrtz_triggers,
	qrtz_job_details,
	qrtz_calendars,
	qrtz_paused_trigger_grps,
	qrtz_scheduler_state,
	qrtz_locks;
