<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-FinanceTracker.Worker.Outbox-f8d665a6-ae7f-4848-8f59-ac722ff187c7</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Quartz" />
        <PackageReference Include="Quartz.Extensions.Hosting" />
        <PackageReference Include="ZLogger" />
        <PackageReference Include="Quartz.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\FinanceTracker.Contracts\FinanceTracker.Contracts.csproj" />
        <ProjectReference Include="..\FinanceTracker.Infrastructure\FinanceTracker.Infrastructure.csproj" />
        <ProjectReference Include="..\FinanceTracker.Worker.Shared\FinanceTracker.Worker.Shared.csproj" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>
</Project>